export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_STUDENTS = "GET_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const GET_STUDENT = "GET_STUDENT";
export const GET_STUDENT_STATS = "GET_STUDENT_STATS";
export const GET_TIMETABLE = "GET_TIMETABLE";
export const GET_TRANSCRIPT = "GET_TRANSCRIPT";
export const GET__ADVISOR_STUDENTS = "GET__ADVISOR_STUDENTS";
export const GET_ADVISOR_TIMETABLE = "GET_ADVISOR_TIMETABLE";
export const GET_AUTO_COURSE = "GET_AUTO_COURSE";
export const COURSES_TO_APPROVE = "COURSES_TO_APPROVE";
export const COURSE_APPROVED = "COURSE_APPROVED";
export const GET_CHAIRMAN_STATS = "GET_CHAIRMAN_STATS";
export const GET_PREDICTED_CGPA = "GET_PREDICTED_CGPA";


export const GET_DEPARMENTS = "GET_DEPARMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";

export const GET_ADVISOR = "GET_ADVISOR";
export const ADD_ADVISOR = "ADD_ADVISOR";

    
export const GET_COURSES = "GET_COURSES";
export const ADD_COURSE = "ADD_COURSE";

export const GET_GROUPS = "GET_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const GET_DEPARTMENT_GROUP = "GET_DEPARTMENT_GROUP";


//  Error actions
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
// Success message
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";


export const GET_BUILDINGS = "GET_BUILDINGS";
export const ADD_BUILDINGS = "ADD_BUILDINGS";


export const GET_ROOMS = "GET_ROOMS";
export const ADD_ROOM = "ADD_ROOM";

export const GET_PAYMENT = "GET_PAYMENT";
export const ADD_PAYMENT = "ADD_PAYMENT";


export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";
export const RES_SIDEBAR = "RES_SIDEBAR";


export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT";


export const GET_CHAIRMANS = "GET_CHAIRMANS";
export const ADD_CHAIRMANS = "ADD_CHAIRMANS";
export const GET_YEAR = "GET_YEAR";